version: '3.3'

services:
  mysql:
    container_name: 'wpab-mysql'
    image: 'mysql:5.7'
    ports:
      - 18766:3306
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password

  phpmyadmin:
    container_name: 'wpab-phpmyadmin'
    depends_on:
      - mysql
    image: 'phpmyadmin/phpmyadmin:latest'
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: 'mysql:3306'
      PMA_USER: wordpress_user
      PMA_PASSWORD: wordpress_password

  wordpress:
    container_name: 'wpab-wordpress'
    depends_on:
      - mysql
    image: 'wordpress:latest'
    ports:
      - '8000:80'
    environment:
      WORDPRESS_DB_HOST: 'mysql:3306'
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - ".:/var/www/html/wp-content/plugins"